class LocalizationMap {
  static Map<String, String> get codesEN => {
        "select_your_language": "Select your language",
        "select_language": "Select Language",
        "get_started": "Get Started",
        "english": "English",
        "age": "age",
        "amount": "Amount",
        "fatigue": "Fatigue 😴",
        "nausea": "Nausea 🤢",
        "cramps": "Cramps 😖",
        "irritability": "Irritability 😠",
        "breast_pain": "Breast Pain 🤕",
        "back_pain": "Back Pain 💥",
        "headaches": "Headaches 🤯",
        "bloating": "Bloating 🌬",
        "mood_swings": "Mood Swings 😣",
        "food_cravings": "Food Cravings 🍫",
        "per_month": "Per Month",
        "per_week": "Per Week",
        "per_year": "Per Year",
        "weight": "Weight",
        "write_note": "Write Note",
        "ovulation_day": "Ovulation day",
        "explain_your_day": "Explain your day.",
        "mood": "Mood",
        "52kg": "52 Kg’s",
        "kg": "Kg’s",
        "lbs": "lbs",
        "8Hr": "8 Hr’s",
        "menstrual_flow": "Menstrual Flow",
        "cramps_acne_diarrhea": "Cramps, Acne, Diarrhea",
        "what_is_the_intensity_of_your_period":
            "What is the intensity of your period?",
        "current_weight": "Current Weight",
        "current_period": "Current Period",
        "Did_you_loss_weight": "Did you loss weight?",
        "what_medications_are_you_using": "What Medications are you using?",
        "what_contraceptive_method_are_you_using":
            "What Contraceptive are you using?",
        "51": "51",
        "weight": "Weight",
        "confirm": "Confirm",
        "edit_info": "Edit Information",
        "kg": "kg’s",
        "sleep": "Sleep",
        "calendar": "Calendar",
        "first_day_of_week": "First Day Of Week",
        "whatsapp": "Whatsapp",
        "messenger": "Messenger",
        "voice_call": "Voice call",
        "chat": "Chat",
        "no_flow": "No Flow",
        "low": "Low",
        "normal": "Normal",
        "medium": "Medium",
        "heavy": "heavy",
        "how_long_you_sleep": "How long you sleep?",
        "8": "8",
        "Hr’s": "Hr’s",
        "mood_sub": "How are you feeling today.",
        "period": "Period",
        "calm": "Calm",
        "happy": "Happy",
        "sad": "Sad",
        "energetic": "Energetic",
        "irritable": "Irritable",
        "fertile_period": "Fertile Period",
        "pregnancy": "Pregnancy",
        "hello": "Hello Sarah",
        "select_symptoms": "Select Symptoms",
        "symptoms": "Symptoms",
        "symptoms_sub": "How are you feeling today.",
        "next": "Next",
        "constipation": "Constipation",
        "welcome": "Welcome",
        "enter_name": "Enter Name",
        "enter_age": "Enter age",
        "enter_cycle_length": "Enter Cycle Length",
        "enter_period_length": "Enter Period Length",
        "onboard_disc1": "We will help you to understand your body",
        "onboard_disc2": "Track your cycle and symptoms with ease daily",
        "onboard_disc3": "Track pregnancy growth and key milestones.",
        "onboard_disc4": "Track health, mood, and lifestyle with ease.",
        "whats_your_name": "What’s your name?",
        "whats_your_age": "What’s your age?",
        "upload_your_photo": "Upload your photo",
        "Choose_your_avatar": "Choose your avatar",
        "add_your_last_period": "Add your last period",
        "today": "Today",
        "cycles": "Cycles",
        "periods": "Periods",
        "this_week_cycle": "This Week Cycle",
        "cycle_length": "Cycle Length",
        "how_many_days_are_in_your_cycle": "How many days are in your cycle?",
        "period_length": "Period Length",
        "how_many_days_your_period_last": "How many days your period last?",
        "what_are_your_cycle_symptoms": "What are your cycle symptoms?",
        "select_medications": "Select Medications",
        "select_contraceptive_method": "Select Contraceptive Method",
        "contraceptive_method": "Contraceptive Method",
        "IUD": "IUD ⚙",
        "birth_control_pill": "Birth Control Pill  💊",
        "emergency_contraceptive_pill": "Emergency Contraceptive Pill ⏳",
        "condom": "Condom 🟡",
        "specify_which_one": "Specify Which One 📝",
        "medications": "Medications",
        "sleeping_pill": "Sleeping Pill",
        "Headache_pill": "Headache Pill",
        "what_are_your_medical_concerns": "What are your medical concerns?",
        "continue_with_google": "Continue with Google",
        "continue_with_facebook": "Continue with Facebook",
        "continue_with_email": "Continue with Email",
        "continue_with_phone_num": "Continue with Phone Num",
        "already_have_an_account": "Already have an account?\t",
        "login": "Login",
        "sd_card": "SD Card",
        "restore_previous_data": "Restore Previous Data",
        "mobile_device": "Mobile Device",
        "backup": "Backup",
        "menstrual_cycles": "Menstrual Cycles",
        "_fahrenheit": "° F",
        "_celsius": "° C",
        "temperature": "Temperature",
        "avg_per_week": "Avg per week",
        "minimum_amount_of_cycles": "Minimum Amount of Cycles",
        "avg_Amount_of_cycles": "Avg Amount of Cycles",
        "restore_data": "Restore Data",
        "backup_sub": "Select Storage to store your data",
        "sun": "Sun",
        "mon": "Mon",
        "sat": "Sat",
        "general_activity": "General Activity",
        "done": "Done",
        "menstruation_stats": "Menstruation Stats",
        "charts": "Charts",
        "create_pin": "Create PIN",
        "confirm_pin": "Confirm PIN",
        "enable_pin": "Enable PIN",
        "settings": "Settings",
        "calendar_options": "Calendar Options",
        "security": "Security",
        "logo": "LOGO",
        "profile": "Profile",
        "delete_data": "Delete Data",
        "notifications": "Notifications",
        "share": "Share",
        "birthdate": "Birthdate",
        "logout": "Logout",
        "phase2": "Phase 2",
        "change_language": "Change Language",
        "change_password": "Change Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "current_language": "Current Language",
        "backup_and_restore": "Backup and Restore",
        "measure_units": "Measure Units",
        "or": "Or",
        "email": "Email",
        "password": "Password",
        "journal": "Journal",
        "time": "Time",
        "times": "Times",
        "date_and_time": "Date and Time",
        "clicks": "Clicks",
        "kicks": "Kicks",
        "current_week": "current week",
        "count_now": "Count now",
        "track_now": "Track now",
        "kick_counter": "Kick Counter",
        "weight_tracker": "Weight Tracker",
        "mood_tracker": "Mood Tracker",
        "pregnancy_tracker": "Pregnancy Tracker",
        "kick_sub": "Press the button to counting kicks",
        "yesterday": "Yesterday",
        "date": "Date",
        "gain": "Gain",
        "gained": "Gained",
        "released": "Released",
        "weight_changes": "Weight Changes",
        "weight_before_pregnancy": "Weight Before Pregnancy",
        "your_edit_information_have_been_successfully_saved":
            "Your Edit Information Have Been Successfully Saved",
        "confirm_password": "Confirm Password",
        "sign_up": "Sign up",
        "date_of_birth": "Date of birth",
        "forgot_password": "Forgot Password?",
        "don’t_have_an_account": "Don’t have an account?\t",
        "remind_to_check_weight": "Remind to check weight",
        "": "",
        "how_are_you_feeling_right_now": "How are you feeling right now?",
        "happiness": "Happiness",
        "joy": "Joy",
        "emotions": "Emotions",
        "excitement": "Excitement",
        "satisfaction": "satisfaction",
        "love": "Love",
        "gratitude": "Gratitude",
        "affection": "Affection",
        "enthusiasm": "Enthusiasm",
        "cheerful": "Cheerful",
        "contentment": "Contentment",
        "frustration": "Frustration",
        "fear": "Fear",
        "surprise": "Surprise",
        "sadness": "Sadness",
        "anger": "Anger",
        "pain": "Pain",
        "weeks": "Weeks",
        "days": "Days",
        "baby_size": "Baby Size",
        "boredom": "Boredom",
        "boredom": "Boredom",
        "pregnancy_%": "Pregnancy %",
        "indifference": "Indifference",
        "save": "Save",
        "result": "Result",
        "calculate": "Calculate",
        "of_pregnancy": " of pregnancy.",
        "last_period": "Last Period",
        "calculate_based_on": "Calculate based on",
        "last_period_date": "Last period date",
        "You_are_currently_at_week": "You are currently at week #23",
        "22_weeks_6_days_or_5_months_7_days":
            "(22 weeks 6 days or 5 months 7 days)",
      };

  static String getTranslatedValues(String key) {
    return codesEN[key] ?? "Text not found";
  }
}

extension Localize on String {
  String L() {
    return LocalizationMap.getTranslatedValues(this);
  }
}
